---
kind: pipeline
name: app

steps:
  - name: build
    image: plugins/docker
    settings:
      registry: ghcr.io
      username: simoneromano96
      # password: 
      #   from_secret: token
      repo: ghcr.io/simoneromano96/graphql-todo/backend
      context: .
      dockerfile: ./.docker/app.dockerfile
      auto_tag: true
      target: production
      config:
        from_secret: docker_auth_config
