---
kind: pipeline
name: build

steps:
  - name: build
    image: plugins/docker
    settings:
      registry: ghcr.io
      username: simoneromano96
      password: 
        from_secret: token
      repo: ghcr.io/simoneromano96/graphql-todo/backend
      context: .
      dockerfile: ./.docker/app.dockerfile
      auto_tag: true
      target: production
      config:
        from_secret: docker_auth_config

---
kind: pipeline
type: ssh
name: deploy

server:
  host:
    from_secret: host
  user:
    from_secret: user
  port:
    from_secret: port
  ssh_key:
    from_secret: ssh_key

steps:
  - name: deploy-docker-api
    commands:
      - cd ~/docker/streams/graphql-todo
      - docker-compose pull api && docker-compose stop api && docker-compose rm -f api && docker-compose up api

depends_on:
  - build

trigger:
  event:
    - promote
    - rollback
